---
title: "Processing of OE 10X data for COVID19 work"
author: "Koen Van den Berge"
date: "3/30/2020"
output: html_document
---



```{r pkg}
here::set_here()
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(rgl)
  library(clusterExperiment)
  library(RColorBrewer)
  library(ggplot2)
  library(dplyr)
})
colby <- function(values, g=4){
  if(is(values, "character")){
    cols <- as.numeric(as.factor(values))
    return(cols)
  }
  if(is(values, "factor")){
    ncl <- nlevels(values)
    if(ncl > 9){
          colpal <- c(RColorBrewer::brewer.pal(9, 'Set1'), wesanderson::wes_palette("Darjeeling1", n=ncl-9, type="continuous"))
    } else {
       colpal <- RColorBrewer::brewer.pal(9, 'Set1')
    }
    cols <- colpal[as.numeric(values)]
    return(cols)
  }
  if(is(values, "numeric")){
    pal <- wesanderson::wes_palette("Zissou1", n=g, type="continuous")
    gg <- Hmisc::cut2(values, g=g)
    if(nlevels(gg) < g){
      nl <- nlevels(gg)
      if(nl == 2) pal <- pal[c(1,g)]
    }
    cols <- pal[gg]
    return(cols)
  }
}
cols <- brewer.pal(9,'Set1')

```

# Import data


```{r loadData}
dataDir <- "../data"
cl <- readRDS(paste0(dataDir,"/cl_OE.rds"))
load(paste0(dataDir,"/regenK5_scone_none,fq,ruv_k=1,no_bio,batch_rsec_adjP_mergecutoff_0.01_20190609_085359.Rda"))
subset <- readRDS(paste0(dataDir,"/subset_index.rds"))
batch <- droplevels(colData(cl2)$batch[subset])
counts <- assays(cl2)$counts[,subset]
timePoint <- as.character(colData(cl2)$batch[subset])
timePoint <- factor(unlist(lapply(strsplit(timePoint, split="_"), "[[", 1)),
                    levels=c("24HPI", "48HPI", "96HPI", "7DPI", "14DPI", "Mix"))
```

# Remove doublets

```{r}
# Remove Doublets
doublets <- read.csv(paste0(dataDir,"/doublet_prediction_sample.csv"), stringsAsFactors = FALSE)
hist(doublets$doubletFinderScore)

doubID <- which(doublets$doubletFinderPred)
doubletCells <- doublets$cell[doubID] #271 doublets (~1%)

counts_noDoubs <- counts[,-doubID]
timePoint_noDoubs <- timePoint[-doubID]
cl_noDoubs <- cl[-doubID]
```


# Dimensionality reduction

```{r eda}
library(uwot)
library(irlba)

### top 100 PCs
set.seed(15)
fVar <- rowVars(counts_noDoubs)
fMean <- rowMeans(counts_noDoubs)
highVarFeatures <- order(fVar, decreasing=TRUE)[1:500]
pcIk <- irlba(log1p(counts_noDoubs[highVarFeatures,]), nv=100)

umIk50 <- uwot::umap(pcIk$v, n_components=3)
rownames(umIk50) <- colData(cl2)$samples[subset][-doubID]
plot(umIk50,  col=alpha(brewer.pal(6,'Set1')[timePoint_noDoubs],.4), pch=16, cex=1/2,
     xlab="UMAP1", ylab="UMAP2", bty='l')
legend("bottomright",levels(timePoint),pch=16,col=brewer.pal(6,'Set1'), bty='n')
plot(umIk50,  col=alpha(brewer.pal(9,'Set1')[factor(cl_noDoubs)],.4), pch=16, cex=1/2,
     xlab="UMAP1", ylab="UMAP2", bty='l')
oldCelltype <- c("SUS", "IN3", "rHBC", "IN2", "GBC", "Neuron", "IN1", "HBC", "MV")
oldCelltype <- factor(oldCelltype, levels=oldCelltype)
legend("bottomright",levels(oldCelltype),pch=16,col=brewer.pal(9,'Set1'), bty='n')


plot3d(umIk50, aspect = 'iso', col=brewer.pal(9,'Set1')[factor(cl_noDoubs)], alpha=.3)
plot3d(umIk50, aspect = 'iso', col=brewer.pal(6,'Set1')[timePoint_noDoubs], alpha=.3)
``` 



# Interpreting (some of) the islands

```{r}
# 24h and 48h cells at mature neuron stage are true neurons => some neurons slipped through
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Omp",]), alpha=.3)
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Scg2",]), alpha=.3)
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Neurod1",]), alpha=.3)

# SUS
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Cyp2g1",]), alpha=.3)
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Cyp1a2",]), alpha=.3)
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Vmo1",]), alpha=.3)
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Muc2",]), alpha=.3)

# HBC
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Krt5",]), alpha=.3)
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Krt14",]), alpha=.3)
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Krt15",]), alpha=.3)
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Trp63",]), alpha=.3)
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Gpr87",]), alpha=.3)

# GBC
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Sprr1a",]), alpha=.3)
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Ascl1",]), alpha=.3)
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Prim1",]), alpha=.3)
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Tk1",]), alpha=.3)
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Plk1",]), alpha=.3)

# MV
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Ascl3",]), alpha=.3)
plot3d(umIk50, aspect = 'iso', col=colby(counts_noDoubs["Trpm5",]), alpha=.3)
```

# Remove chronologically asyncrhonous cells (bridge, mature neuron 24/48h cells)

## Bridge cells

```{r}
plot3d(umIk50, aspect = 'iso', 
       col=cols[timePoint_noDoubs], 
       alpha=.6)


bridgeRegionID <- (umIk50[,1] < -3.3 & umIk50[,1] > -4.5) & (umIk50[,2] < 0)
plot3d(umIk50, aspect = 'iso', 
       col=colby(factor(bridgeRegionID), g=2), alpha=.6)
bridgeAllCells <- which(bridgeRegionID)
bridgeID <- bridgeAllCells[timePoint_noDoubs[bridgeAllCells] %in% levels(timePoint_noDoubs)[1:3]]
# plot cells to be removed
bridgeLogical <- vector(length=nrow(umIk50))
bridgeLogical[bridgeID] <- TRUE
plot3d(umIk50, aspect = 'iso', 
       col=colby(factor(bridgeLogical), g=2), alpha=.4)

bridgeCellNames <- rownames(umIk50)[bridgeID]
rm(bridgeLogical, bridgeAllCells) 
```

## Mature neuron 24/48h

```{r}
plot3d(umIk50, aspect = 'iso', 
       col=cols[timePoint_noDoubs], 
       alpha=.6)

mnCellID <- which(umIk50[,1] < -6.5)
mnCellID <- mnCellID[timePoint_noDoubs[mnCellID] %in% levels(timePoint_noDoubs)[1:2]]
mnLogical <- vector(length=nrow(umIk50))
mnLogical[mnCellID] <- TRUE
plot3d(umIk50, aspect = 'iso', 
       col=colby(factor(mnLogical), g=2), alpha=.4)

rm(mnLogical)
```

## Remove these

```{r}
rmAsync <- c(bridgeID, mnCellID)

umIk50_async <- umIk50[-rmAsync,]
counts_noDoubs_async <- counts_noDoubs[,-rmAsync]
timePoint_noDoubs_async <- timePoint_noDoubs[-rmAsync]
cl_noDoubs_async <- cl_noDoubs[-rmAsync]
```

# Dimensionality reduction

## High variable genes

```{r}
highVarFeatures <- order(rowVars(counts_noDoubs_async), decreasing=TRUE)[1:500]

set.seed(9)
pc100 <- irlba(log1p(counts_noDoubs_async[highVarFeatures,]), nv=100)
umDR <- uwot::umap(pc100$v,  n_components=2, ret_model = TRUE)

plot(umDR$embedding[,1:2], col=cols[timePoint_noDoubs_async], pch=16, cex=1/2,
     xlab="UMAP1", ylab="UMAP2", bty='l')
legend("topright", legend=levels(timePoint_noDoubs_async), col=cols[1:nlevels(timePoint_noDoubs_async)], pch=16, bty='n')
```

## Save files

```{r, eval=FALSE}
cn <- colData(cl2)$samples[subset][-doubID][-rmAsync]
colnames(counts_noDoubs_async) <- cn
saveRDS(counts_noDoubs_async, file="../data/filteredAsync/counts.rds")
names(timePoint_noDoubs_async) <- cn
saveRDS(timePoint_noDoubs_async, file="../data/filteredAsync/timePoint.rds")
names(cl_noDoubs_async) <- cn
saveRDS(cl_noDoubs_async, file="../data/filteredAsync/cl.rds")
saveRDS(umDR, file="../data/filteredAsync/umapEmbedding.rds")
```

# Session info

```{r}
sessionInfo()
```

